export const recomendations = [
    {
        "id" : "1",
        "image" : "./src/images/recomendation-1.svg",
        "name" : "Витамин Д Д3 D D3 капсулы 2000 МЕ 90 шт, БАД для иммунитета, витаминный комплекс для здор...",
        "currentPrice" : "869 ₽",
        "fullPrice" : "1269 ₽",
        "discount" : "-30%",
        "isNew" : "no",
        "isThreeForTwo" : "no",
        "isProductOfTheWeek" : "no",
    },
    {
        "id" : "2",
        "image" : "./src/images/recomendation-2.svg",
        "name" : "Витамин Д Д3 D D3 капсулы 2000 МЕ 90 шт, БАД для иммунитета, витаминный комплекс для здор...",
        "currentPrice" : "869 ₽",
        "fullPrice" : "",
        "discount" : "",
        "isNew" : "no",
        "isThreeForTwo" : "no",
        "isProductOfTheWeek" : "no",
    },
    {
        "id" : "3",
        "image" : "./src/images/recomendation-3.svg",
        "name" : "Витамин Д 3 5000 ME 120 капсул ",
        "currentPrice" : "869 ₽",
        "fullPrice" : "1269 ₽",
        "discount" : "-30%",
        "isNew" : "yes",
        "isThreeForTwo" : "yes",
        "isProductOfTheWeek" : "yes",
    },
    {
        "id" : "4",
        "image" : "./src/images/recomendation-4.svg",
        "name" : "Витамин Д Д3 D D3 капсулы 2000 МЕ 90 шт, БАД для иммунитета, витаминный комплекс для здор...",
        "currentPrice" : "869 ₽",
        "fullPrice" : "",
        "discount" : "",
        "isNew" : "yes",
        "isThreeForTwo" : "no",
        "isProductOfTheWeek" : "yes",
    },
    {
        "id" : "5",
        "image" : "./src/images/recomendation-1.svg",
        "name" : "Витамин Д Д3 D D3 капсулы 2000 МЕ 90 шт, БАД для иммунитета, витаминный комплекс для здор...",
        "currentPrice" : "869 ₽",
        "fullPrice" : "1269 ₽",
        "discount" : "-30%",
        "isNew" : "no",
        "isThreeForTwo" : "no",
        "isProductOfTheWeek" : "no",
    },
    {
        "id" : "6",
        "image" : "./src/images/recomendation-2.svg",
        "name" : "Витамин Д Д3 D D3 капсулы 2000 МЕ 90 шт, БАД для иммунитета, витаминный комплекс для здор...",
        "currentPrice" : "869 ₽",
        "fullPrice" : "",
        "discount" : "",
        "isNew" : "no",
        "isThreeForTwo" : "yes",
        "isProductOfTheWeek" : "no",
    },
    {
        "id" : "7",
        "image" : "./src/images/recomendation-3.svg",
        "name" : "Витамин Д 3 5000 ME 120 капсул ",
        "currentPrice" : "869 ₽",
        "fullPrice" : "1269 ₽",
        "discount" : "-30%",
        "isNew" : "yes",
        "isThreeForTwo" : "yes",
        "isProductOfTheWeek" : "yes",
    },
    {
        "id" : "8",
        "image" : "./src/images/recomendation-4.svg",
        "name" : "Витамин Д Д3 D D3 капсулы 2000 МЕ 90 шт, БАД для иммунитета, витаминный комплекс для здор...",
        "currentPrice" : "869 ₽",
        "fullPrice" : "",
        "discount" : "",
        "isNew" : "no",
        "isThreeForTwo" : "no",
        "isProductOfTheWeek" : "no",
    },
]